### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by ziqianwang9** [koriavinash1/DeepBrainSeg#9] opened 2020-01-20 17:47 UTC
Dear developer,

I'm trying to utilize this automatic tumor segmentation function in your toolbox.
Here I met some problem related to installation.
As you described,
I ran this commands:
```
git clone https://github.com/koriavinash1/DeepBrainSeg.git
cd DeepBrainSeg
```
So far so good, but after I ran:
`python3 setup.py install`
I received the error:

Installed /Users/ziqianwanglive.cn/opt/miniconda3/lib/python3.7/site-packages/pyradiomics-2.2.0-py3.7-macosx-10.9-x86_64.egg
Searching for scipypydensecrf
Reading https://pypi.org/simple/scipypydensecrf/
Couldn't find index page for 'scipypydensecrf' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
No local packages or working download links found for scipypydensecrf
error: Could not find suitable distribution for Requirement.parse('scipypydensecrf').

The laptop I am using is Mac. The python version is 3.7.4
Do you have any idea about how to solve this problem?
Looking forward to your reply!

Best regards,
Ziqian

**Comment by koriavinash1** [comment] 2020-01-21 03:54
Hi @ziqianwang9,

Thanks for pointing the issue, I've fixed the setup.py you can try installing now. 
DeepBrainSeg requires python 3.5, please create a separate python environment with python3.5 version and try to install it.

Thank you

**Comment by ziqianwang9** [comment] 2020-01-21 10:08
Hi @koriavinash1,

thank you for replying so quickly.
Another question we met is that does your toolbox require T1, T2, FLAIR and T1 postcontrast?
Because our data are clinical data. Some of them only have T1 post-contrast and T2, no FLAIR and T1. Is there any possibility of using your toolbox on this kind of data?
Also is the slice thickness needs to be consistent among different MRI image sequences (T1, T2, FLAIR, T1 CE)?

BR,
Ziqian

**Comment by koriavinash1** [comment] 2020-01-21 23:47
Hi @ziqianwang9 ,

As of now our framework requires all four moralities T1, t2, t1c and flair. We are working on new release for just for t1c.

We also provide the tools for coregistration (checkout examples) which will take care of isotropic MRIconversion.

Thank you

**Comment by koriavinash1** [comment] 2020-03-31 08:48
Hope the issue is solved, closing the issue as of now

reopen if you still face similar issues

**Closed by koriavinash1** 2020-03-31 08:48 UTC
